title = "Azrak the Wall-Eater"
image = "azrak.png"
content_file = "azrak.md"

[infobox]
"Espèce" = "Devourer Papoute"
"Genre" = "M"
"Domain" = "Hunger & Destruction"
"Enemy of" = "Entire buildings"
"Mother" = "Voidmother"

