title = "Lumina the Warm One"
category = "Characters"
image = "lumina.png"
content_file = "lumina.md"

[infobox]
"Espèce" = "Radiant Papoute"
"Genre" = "F"
"Domain" = "Comfort & heat"
"Children" = "Bernardo"
"Mother" = "Voidmother"

